### ISSUE TITLE
Problems with multi class classification

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/setfit#131]
Hi,
I have multiple problems with multi class classification.

The README sais that if you do multi class classification you must specify `multi_target_strategy`.

The strange thing is that all works fine with multiple classes when I do **NOT** add `multi_target_strategy`.

But when I specify `multi_target_strategy` the code complains with:

```
>> trainer created, start training
Traceback (most recent call last):
  File "/home/phmay/dev/set_fit_frag_magenta/15_fit.py", line 60, in <module>
    trainer.train()
  File "/home/phmay/miniconda3/envs/paraphrase-mining/lib/python3.9/site-packages/setfit/trainer.py", line 255, in train
    train_examples = sentence_pairs_generation_multilabel(
  File "/home/phmay/miniconda3/envs/paraphrase-mining/lib/python3.9/site-packages/setfit/modeling.py", line 257, in sentence_pairs_generation_multilabel
    sample_labels = np.where(labels[first_idx, :] == 1)[0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

What did I miss? Is my data format wrong? IMO the README should document this.

Can any1 please help?

**Comment by PhilipMay** [comment]
Well, I confused multi label with multi class I guess. Closing this again. Sorry.
