### ISSUE TITLE
[Bug] Error when initializing `DistillationSetFitTrainer` without `train_dataset`

### ISSUE THREAD

**Issue by tomaarsen** [huggingface/setfit#189]
Hello!

## How to Reproduce
<details><summary>Copy-pasteable reproducing script (Script 1)</summary>

```python
from setfit import SetFitModel, DistillationSetFitTrainer

model: SetFitModel = SetFitModel.from_pretrained(
    "sentence-transformers/paraphrase-mpnet-base-v2"
)

# These parameters are nonsensical, but they allow for quickly showing the bug
trainer = DistillationSetFitTrainer(teacher_model=model, student_model=model)
trainer.train()
```
</details>

Running this script gives the following error:

```python
Traceback (most recent call last):
  File "[sic]\setfit\demo_distillation_no_train_ds.py", line 10, in <module>
    trainer.train()
  File "[sic]\setfit\src\setfit\trainer_distillation.py", line 138, in train
    self._validate_column_mapping(self.train_dataset)
  File "[sic]\setfit\src\setfit\trainer.py", line 134, in _validate_column_mapping
    column_names = set(dataset.column_names)
AttributeError: 'NoneType' object has no attribute 'column_names'
```

For reference, if I neglect to add a `train_dataset` to the regular `SetFitTrainer`, then I get the following:
<details><summary>Copy-pasteable reproducing script (Script 2)</summary>

```python
from setfit import SetFitModel, SetFitTrainer

model: SetFitModel = SetFitModel.from_pretrained(
    "sentence-transformers/paraphrase-mpnet-base-v2"
)
trainer = SetFitTrainer(model)
trainer.train()
```
</details>

```python
Traceback (most recent call last):
  File "[sic]\setfit\demo_trainer_no_train_ds.py", line 8, in <module>
    trainer.train()
  File "[sic]\setfit\src\setfit\trainer.py", line 290, in train
    raise ValueError("SetFitTrainer: training requires a train_dataset.")
ValueError: SetFitTrainer: training requires a train_dataset.
```

## Expected behaviour
I would expect a warning to be displayed, exactly like with the regular `SetFitTrainer`.

## What now?
I'll open up a PR to handle this.

- Tom Aarsen

**Comment by orenpereg** [comment]
Good catch! thank you Tom
