### ISSUE TITLE
Very low and inaccurate prediction probabilities for multi-class classification

### ISSUE THREAD

**Issue by aaronbriel** [huggingface/setfit#479]
I'm seeing very low and inaccurate prediction probabilities for a relatively simple multi-class classification problem. I have 30 classes with 50 samples per class. The classes represent intent of text, with samples that have been hand-selected and clear cut. The 'busy' intent, for example, has an exact sample of "i'm busy". However, a prediction with that exact text yields low probabilities across the board:
```
>>> from setfit import SetFitModel
>>> model = SetFitModel.from_pretrained('models')
>>> model.predict_proba(['im busy'])

tensor([[0.0597, 0.0310, 0.0330, 0.0333, 0.0391, 0.0294, 0.0522, 0.0390, 0.0428,
         0.0349, 0.0404, 0.0556, 0.0358, 0.0381, 0.0431, 0.0470, 0.0343, 0.0295,
         0.0278, 0.0273, 0.0328, 0.0290, 0.0351, 0.0411, 0.0423, 0.0464]],
       device='cuda:0', grad_fn=<SoftmaxBackward0>)
```

My apologies that the following information is repeated in issue #478, but I felt that this accuracy issue warranted a second ticket. 

Here is how I configured the dataset to be compatible for SetFit training:

```
from datasets import concatenate_datasets, load_dataset
import pandas as pd
from setfit import SetFitModel, Trainer, TrainingArguments
from transformers import (
    AutoTokenizer,
    EvalPrediction,
    EarlyStoppingCallback
)

try:
    df = pd.read_csv(self.data_file, encoding='utf-8')
except FileNotFoundError as exc:
    raise FileNotFoundError(f"Data file not found: {self.data_file}") from exc

labels = df['label'].unique().tolist()

# Load the full dataset
full_dataset = load_dataset('csv', data_files=self.data_file)['train']
train_subsets = []
eval_subsets = []
test_subsets = []

# Applying stratification to ensure balanced train and test subsets
unique_labels = full_dataset.unique('label_text')
for unique_label in unique_labels:
    # Filter the dataset for the current label
    label_dataset = full_dataset.filter(lambda example: example['label_text'] == unique_label)

    # Shuffle the dataset for this label
    label_dataset = label_dataset.shuffle(seed=42)

    # Split the dataset for this label into train and test subsets
    train_subset = label_dataset.select(range(30))
    eval_subset = label_dataset.select(range(30, 40))
    test_subset = label_dataset.select(range(40, 50))

    # Add the subsets to the respective lists
    train_subsets.append(train_subset)
    eval_subsets.append(eval_subset)
    test_subsets.append(test_subset)

# Concatenate the subsets to form the final train and test datasets
train_dataset = concatenate_datasets(train_subsets)
eval_dataset = concatenate_datasets(eval_subsets)
test_dataset = concatenate_datasets(test_subsets)

# Shuffle the final datasets
train_dataset = train_dataset.shuffle(seed=42)
eval_dataset = eval_dataset.shuffle(seed=42)
test_dataset = test_dataset.shuffle(seed=42)
```

Here is how I set up training, based on suggestions given by @tomaarsen [here](https://github.com/huggingface/setfit/issues/408):

```
model = SetFitModel.from_pretrained(
    'sentence-transformers/paraphrase-mpnet-base-v2',
    use_differentiable_head=True,
    head_params={"out_features": len(intents)},
)
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-mpnet-base-v2')

model.labels = df['label'].unique().tolist()

timestamp = datetime.now().strftime("%Y%m%d%H%M%S")

args = TrainingArguments(
    logging_steps=10,
    run_name=timestamp,
    eval_steps=50,
    save_steps=50,
    batch_size=64,
    load_best_model_at_end=True
)
callbacks = [EarlyStoppingCallback(early_stopping_patience=5)] \
    if add_early_stopping else []

trainer = Trainer(
    model=self.model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    callbacks=callbacks
)

trainer.train()
```

Any suggestions for improvement would be greatly appreciated!

**Comment by tomaarsen** [comment]
Hello!

Based on #478, it seems that your embedding model has been finetuned successfully, but that your classifier failed to train. The natural consequence is that the classifier has no idea what to do with the trained embeddings, and you end up with a relatively "even" classification like this. My recommendation is to instead move to a [logistic regression head](https://huggingface.co/docs/setfit/how_to/classification_heads#logistic-regression-classification-head).

If you want to avoid re-training the model, then I think you should be able to reuse the embedding model & freshly train only the second phase (the classifier):

```python
from setfit import SetFitModel
from sklearn.linear_model import LogisticRegression
model = SetFitModel.from_pretrained('models')
model.model_head = LogisticRegression()

# prepare your data like before

trainer = Trainer(
    model=model,
    args=args,
)
trainer.train_classifier(train_dataset["text"], train_dataset["label"])
# ^ This should train very quickly, with no logs
metrics = trainer.evaluate(eval_dataset)
print(metrics)

print(model.predict("I'm busy"))
```

Also, as a little bonus, you can also specify your label names in the `SetFitModel.from_pretrained`, e.g. `SetFitModel.from_pretrained("...", labels=["economy", "business", "sports'])`. Then your `model.predict()` will just output the string labels, which can be convenient.

- Tom Aarsen

**Comment by aaronbriel** [comment]
Thank you so much for the quick response!

Looks like this would also require running `fit` with the LogisticRegression instance:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/venv/lib/python3.11/site-packages/setfit/modeling.py", line 503, in predict_proba
    probs = self.model_head.predict_proba(embeddings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py", line 1374, in predict_proba
    check_is_fitted(self)
  File "/home/ubuntu/anaconda3/envs/venv/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1461, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
>>> model.predict(['im busy'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/venv/lib/python3.11/site-packages/setfit/modeling.py", line 543, in predict
    preds = self.model_head.predict(embeddings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/venv/lib/python3.11/site-packages/sklearn/linear_model/_base.py", line 451, in predict
    scores = self.decision_function(X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/venv/lib/python3.11/site-packages/sklearn/linear_model/_base.py", line 429, in decision_function
    check_is_fitted(self)
  File "/home/ubuntu/anaconda3/envs/venv/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1461, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
```

I'm going to go ahead and re-train the model using a subset of data as you suggested in #479. I'll let you know the results. Thanks again!

**Comment by tomaarsen** [comment]
I believe the `trainer.train_classifier(...)` from my snippet should take care of fitting the Logistic Regression head, but you're also free to retrain as well! Wishing you luck :)

- Tom Aarsen

**Comment by aaronbriel** [comment]
I retrained the model with a subset and it is working flawlessly! I'm extremely impressed with the prediction speed as well. Thanks again for the fast responses and stellar assistance here!

**Comment by aaronbriel** [comment]
I retrained the model with a subset and it is working flawlessly! I'm extremely impressed with the prediction speed as well. Thanks again for the fast responses and stellar assistance here!
