### ISSUE TITLE
`TypeError: __init__() got an unexpected keyword argument '_name_or_path'` for `SetFitModel.from_pretrained`

### ISSUE THREAD

**Issue by harupy** [huggingface/setfit#504]
## How to reproduce the error

```python
from setfit import SetFitModel
SetFitModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
```

## Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py", line 415, in from_pretrained
    instance = cls._from_pretrained(
  File "/usr/local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/setfit/modeling.py", line 869, in _from_pretrained
    return cls(
TypeError: __init__() got an unexpected keyword argument '_name_or_path'
```

## Package versions

```
root@8fcc293f7971:/# pip list
Package               Version
--------------------- -----------
aiohttp               3.9.3
aiosignal             1.3.1
async-timeout         4.0.3
attrs                 23.2.0
certifi               2024.2.2
charset-normalizer    3.3.2
datasets              2.18.0
dill                  0.3.8
evaluate              0.4.1
filelock              3.13.3
frozenlist            1.4.1
fsspec                2024.2.0
huggingface-hub       0.22.0
idna                  3.6
Jinja2                3.1.3
joblib                1.3.2
MarkupSafe            2.1.5
mpmath                1.3.0
multidict             6.0.5
multiprocess          0.70.16
networkx              3.2.1
numpy                 1.26.4
packaging             24.0
pandas                2.2.1
pillow                10.2.0
pip                   23.0.1
pyarrow               15.0.2
pyarrow-hotfix        0.6
python-dateutil       2.9.0.post0
pytz                  2024.1
PyYAML                6.0.1
regex                 2023.12.25
requests              2.31.0
responses             0.18.0
safetensors           0.4.2
scikit-learn          1.4.1.post1
scipy                 1.12.0
sentence-transformers 2.6.0
setfit                1.0.3
setuptools            58.1.0
six                   1.16.0
sympy                 1.12
threadpoolctl         3.4.0
tokenizers            0.15.2
torch                 2.2.1
tqdm                  4.66.2
transformers          4.39.1
typing_extensions     4.10.0
tzdata                2024.1
urllib3               2.2.1
wheel                 0.42.0
xxhash                3.4.1
yarl                  1.9.4
```

**Comment by harupy** [comment]
The code in the issue description works fine with `huggingface_hub==0.21.4`.

**Comment by harupy** [comment]
`_name_or_path` is injected here:

https://github.com/huggingface/huggingface_hub/blame/9e13b839c246d08f0ead380f0b50d8c25aaf9ecf/src/huggingface_hub/hub_mixin.py#L409

**Comment by CalinLucian** [comment]
https://github.com/huggingface/huggingface_hub/issues/2157#issuecomment-2020748224 solved now

**Comment by harupy** [comment]
Thanks!
